### ISSUE TITLE
Makes some link impossible to load

### ISSUE THREAD

**Issue by Cyberavater** [alyssaxuu/screenity#215]
eg lInk: https://filecrypt.co/Container/E0A5E481A8.html

can you make a blacklist to add
`https://filecrypt.co/Container/E0A5E481A8.html (iframe)`

Also, it seems like a issue with newer version.

**Comment by alyssaxuu** [comment]
The page appears to load fine for me, but I do see that other people have had issues with it too with browser extensions in general that inject themselves into the DOM. I don't really want to have to manually add sites with similar issues into the codebase (especially if they don't necessarily stop working in all cases), however I might consider having some additional advanced settings somewhere in the extension to set up a blacklist.

For now though, you can simply paste chrome://extensions/?id=kbbdabhdfibnancpjfhlkhafgdilcnji in the address bar to see the Screenity details page, and under "Site access", you can either have it work on click, which won't inject Screenity automatically in pages, or make it work only for specific sites (sadly no blacklist option). That should solve the problem.

**Comment by Cyberavater** [comment]
Nope, it doesn't fix it. Also, you didn't encounter any error because you didn't get CutCaptcha (if you're on a filecrypt link multiple times then you get cutcaptcha for the first few times recaptcha or simple math). If you're interested to see how bad it is, I suggest you refresh the link I gave you for at least 20 times without solving the captcha.

My current solution is to disable this extension until I next use it or use something else entirely. 

And yes I already tried your trick also,
site access on specific site
*://a.com/*

**Comment by alyssaxuu** [comment]
Ah I see, yes if I reload many times, then I do experience the issue you mention. However, if I set the site settings to on click only here, the problem does go away for me. I don't think there should be anything else impacting the captcha of the site besides injecting the Screenity extension inside the DOM, it's not really doing anything in the background... I could try to investigate more, but like I said, it does seem like the specific website has issues with other extensions as well, not just Screenity.

<img width="875" alt="Screenshot 2024-02-09 at 11 03 53 PM" src="https://github.com/alyssaxuu/screenity/assets/7581348/c7743cc8-ac7f-472e-bffd-4b96bf45e438">
